### PR TITLE
Fixed responsiveness issue

### PR DESCRIPTION
**Pull request by eswarasai**
### Description
- [x] Added `meta` tag for viewport
- [x] Fixed `min-width` style on `body` for mobile and tablet devices

Fixes: #20

### CODE REVIEW

**Comment by eswarasai** [comment]
@ligi -- Can you please review this PR and let me know if there's anything else needed. Thanks :)

**Comment by ligi** [comment]
looks like it could work - but I am not really into web-dev - so perhaps it is better when @thereapman merges it into the slockit faucet - I will then test on my phones

**Comment by ligi** [comment]
@eswarasai just reached  @thereapman - he will have a look tomorrow

**Comment by eswarasai** [comment]
@ligi -- Awesome. Thanks for the update. Will wait for @thereapman to get back with his feedback 👍

**Comment by ligi** [comment]
great - just talked to @thereapman and your pr works nice. https://gitter.im/goerli/testnet?at=5c94901c6a3d2e230d060c0d - is also deployed on the goerli faucet - you should get the bounty

**Comment by eswarasai** [comment]
@ligi -- Awesome. Thanks for the update.

@ceresstation -- Can you please payout the bounty [here](https://gitcoin.co/issue/poanetwork/poa-faucet/20/2640)? Thanks!

**Comment by ligi** [comment]
@eswarasai hope your payout works soon - but I can't trigger it
are you on twitter so at least I could credit you ;-)

tweeted about the change here:

https://twitter.com/wallethapp/status/1111276983571365889

@vbaranov @igorbarinov - can we get a merge here - already lives in production

**Comment by eswarasai** [comment]
@ligi -- Yep, Scott has taken care of the payment once you've confirmed the fix :)

My Twitter profile -- https://twitter.com/eswara_sai

Also, please do let me know if you need any additional help in fixing the issues. Thanks!

**Pull request merged**
